### ISSUE TITLE
rvalue-ref-qualified data() could return by value

### ISSUE THREAD

**Issue by PeterSommerlad** [dbj-systems/dbj--nothing-but#2]
Hi, since nothingbut seems only to work for trivial and relatively small types, I would not mark the ref-qualified data() member functions as `=delete` but would return by value. That makes the type a bit more versatile. the const && case can only be reached with malicious code, so it could be removed, but marking it as deleted is not a problem.
```
                       T const& data() const &  { return val_; }
			// can not get data from temporary 
			T data() const && = delete ;
			// for users to reach to non const data handled
			// ref. qualified since 0.6.0
			T& data() &  { return (T&)val_; } // the cast is unnecessary
			// can not get data from temporary 
			T data() && { return val_; }
```

**Comment by DBJDBJ** [comment]
Accept and understood. Can we have some real-life examples, please?

"... since nothingbut seems only to work for trivial and relatively small types..."

That is by design. It will work with C++ fundamental types "only", not compound types. 

" ... That makes the type a bit more versatile ..." 

Also by design. I somehow do not like "versatile" types, simply because they tend to exhibit surprising behaviour "down the road" :)

" ... can only be reached with malicious code..."

Exactly. Thus let us test the resilience in the presence of malicious code, or as I would put it "pathological use cases".

Thanks for your involvement. Much appreciated. I think that should be added to the documentation.

**Comment by DBJDBJ** [comment]
Please review the "simple" branch.
